### ISSUE TITLE
Fix update model state in main branch

### ISSUE THREAD

**Issue by cguzman95** [open-atmos/camp#3]
Hello @mattldawson ,

I found that the main branch is missing a hotfix discussed a time ago. The change is the following:

![image](https://user-images.githubusercontent.com/52777396/137197348-f0c90386-4d7b-44af-a01d-7c3987959e27.png)

The parameters should be -SMALL or TINY to avoid a division by zero which produces null values and sometimes problems on debugging.

**Comment by mattldawson** [comment]
Hi @cguzman95,

I remember talking about this, but I don't really remember the details. I don't see a problem with making this change, as long as the tests pass. Do you want to do this, or should I?
